[package]
name = "reconstruction_app"
version = "0.1.0"
edition = "2024"

[dependencies]
lib_cv = { path = "../lib_cv" }
opencv = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
